import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { getPages } from '../../sanity/sanity_utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Asif's Portfolio",
  description: 'Generated by Next + Sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pages = await getPages();
  //console.log(pages)
  return (
    <html lang="en">
      <body className='mxw-3xl mx-auto bg-lime-300 p-5 h-screen '>
        <header className='mb-5 flex items-center justify-between'>
          <Link
            href="/"
            className='bg-gradient-to-r from-orange-400 to-purple-600 bg-clip-text text-transparent text-lg drop-shadow font-bold'>
            Muhammad Asif Shahzad
          </Link>
          <div className='flex items-center gap-5 text-gray-600 text-sm'>
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className='hover:underline'>
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main >{children}</main>
      </body>

    </html>
  )
}
